CREATE TABLE "answers" (
                           "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "message_id" varchar,
                           "answer" varchar,
                           "group_id" varchar
);

CREATE TABLE "leaderboard" (
                               "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "candidate_id" varchar UNIQUE,
                               "points" integer DEFAULT 0,
                               "group_id" varchar
);

CREATE TABLE "vote_history" (
                                "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "message_id" varchar,
                                "voter_id" varchar,
                                "group_id" varchar,
                                "option" integer,
                                "is_passed" bool
);