const GROUP_IDs = [
    "919686855796@c.us",
]

const {
    NOTION_QUIZ_DATABASE_ID,
    NOTION_SECRET,
    imagePath,
    UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN,
    QUIZ_COUNTER
} = process.env;

module.exports = {
    GROUP_IDs,
    NOTION_QUIZ_DATABASE_ID,
    NOTION_SECRET,
    imagePath,
    UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN,
    QUIZ_COUNTER
}