const GROUP_IDs = [
    "120363024352793011@g.us",
    "120363029131273696@g.us",
    "120363030881044093@g.us",
]

const DISCORD_API_ORIGIN = "https://discord.com/api/v10"

const {
    NOTION_QUIZ_DATABASE_ID,
    NOTION_SECRET,
    imagePath,
    UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN,
    QUIZ_COUNTER,
    DISCORD_TOKEN,
    DISCORD_CHANNEL_ID
} = process.env;

module.exports = {
    GROUP_IDs,
    DISCORD_API_ORIGIN,
    NOTION_QUIZ_DATABASE_ID,
    NOTION_SECRET,
    imagePath,
    UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN,
    QUIZ_COUNTER,
    DISCORD_TOKEN,
    DISCORD_CHANNEL_ID
}